name: "Submit Form"
description: "Submit your ompany/Product/Service. Content you submit should be ORIGINAL content (re-written from the website/brand) to give it the best chance of ranking higher in Goog."
title: "[SUBMISSION] Company/Product: "
labels: ["submission"]
assignees: []

body:
  - type: input
    id: product_name
    attributes:
      label: "Product Name"
      description: "Official name with correct spelling and letter case (Required)"
      placeholder: "Enter the product name"
    validations:
      required: true

  - type: input
    id: company_name
    attributes:
      label: "Company Name"
      description: "Official name with correct spelling and letter case (Required)"
      placeholder: "Enter the company name"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: "Website URL"
      description: "Official product or company website (Required)"
      placeholder: "https://example.com"
    validations:
      required: true

  - type: dropdown
    id: product_type
    attributes:
      label: "Product Type"
      description: "Select the type of product"
      options:
        - Software
        - Service Provider
        - Info Product

  - type: dropdown
    id: market
    attributes:
      label: "Market"
      description: "Select the market"
      options:
        - B2B
        - B2C

  - type: checkboxes
    id: categories
    attributes:
      label: "Categories"
      description: "Select all applicable categories"
      options:
        - label: "SaaS"
        - label: "Marketing"
        - label: "E-Commerce"
        - label: "Finance"
        - label: "Education"

  - type: textarea
    id: competitors
    attributes:
      label: "Competitors"
      description: "List competitors for your product/service"
      placeholder: "Enter competitor names"

  - type: textarea
    id: features
    attributes:
      label: "Features"
      description: "List key features of your product (Add one per line)"
      placeholder: "Feature 1\nFeature 2\nFeature 3"

  - type: input
    id: feature_page_url
    attributes:
      label: "Feature Page URL"
      description: "Link to a dedicated feature page (Optional)"
      placeholder: "https://example.com/features"

  - type: textarea
    id: short_description
    attributes:
      label: "Short Description"
      description: "Provide a short description. The content you submit should be ORIGINAL content (re-written from the website/brand materials to give it the best chance of being listed favorably, and ranking higher in search engine so more people can find you."
      placeholder: "Brief description of your product"
    validations:
      required: true

  - type: textarea
    id: full_description
    attributes:
      label: "Full Description or article"
      description: "Provide a detailed description, or a full article formatting in markdown showcasing whatever you feel is relevant and helpful. The content you submit should be ORIGINAL content (re-written from the website/brand materials to give it the best chance of being listed favorably, and ranking higher in search engine so more people can find you."
      placeholder: "Long form content"
    validations:
      required: true

  - type: dropdown
    id: pricing
    attributes:
      label: "Pricing"
      description: "Select the pricing model"
      options:
        - Free
        - Paid

  - type: dropdown
    id: model
    attributes:
      label: "Pricing Model"
      description: "Select a pricing model"
      options:
        - Subscription
        - One-time Purchase
        - Freemium

  - type: dropdown
    id: free_trial
    attributes:
      label: "Free Trial Available?"
      options:
        - "Yes"
        - "No"

  - type: dropdown
    id: open_source
    attributes:
      label: "Is this product open-source?"
      options:
        - "Yes"
        - "No"

  - type: input
    id: promo_code
    attributes:
      label: "Promo Code"
      description: "Enter the details for a promo code (Optional)"
      placeholder: "Promo code details"

  - type: input
    id: pricing_page_url
    attributes:
      label: "Pricing Page URL"
      description: "Link to pricing page (Optional)"
      placeholder: "https://example.com/pricing"

  - type: dropdown
    id: referral_program
    attributes:
      label: "Referral Program?"
      options:
        - "Yes"
        - "No"

  - type: dropdown
    id: affiliate_program
    attributes:
      label: "Affiliate Program?"
      options:
        - "Yes"
        - "No"

  - type: input
    id: affiliate_signup_url
    attributes:
      label: "Affiliate Signup URL"
      description: "Provide the affiliate signup link (Optional)"
      placeholder: "https://example.com/affiliate"

  - type: input
    id: logo_url
    attributes:
      label: "Logo URL"
      description: "Link to your company/product logo"
      placeholder: "https://example.com/logo.png"

  - type: input
    id: promo_video_url
    attributes:
      label: "Promo Video URL"
      description: "Link to promo video (Optional)"
      placeholder: "https://youtube.com/promo"

  - type: textarea
    id: social_links
    attributes:
      label: "Social Media Links"
      description: "Provide your social media URLs (One per line)"
      placeholder: "YouTube: https://youtube.com/...\nInstagram: https://instagram.com/..."

  - type: checkboxes
    id: consent
    attributes:
      label: "Consent"
      options:
        - label: "You may upload my videos to your YouTube to promote my brand"
